server:
  port: 8886

mydata:
  patha: file:/C:/room/image/
  pathb: file:/C:/room/life/
  pathc: file:/C:/room/room/
  upload-patha: C:/room/image
  upload-pathb: C:/room/life

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/room?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: true

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.room.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

